//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Calllings = new HashSet<Callling>();
            this.ValunteerEvents = new HashSet<ValunteerEvent>();
        }
    
        public int eventCode { get; set; }
        public Nullable<int> eventNameId { get; set; }
        public string eventDescription { get; set; }
        public double heightPointAddress { get; set; }
        public double widthPointAddress { get; set; }
        public System.DateTime startCallingDate { get; set; }
        public int eventStatusId { get; set; }
        public string stringAddress { get; set; }
        public Nullable<int> city { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Callling> Calllings { get; set; }
        public virtual EventName EventName { get; set; }
        public virtual EventStatu EventStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValunteerEvent> ValunteerEvents { get; set; }
    }
}
