//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryStatusValunteer
    {
        public int id { get; set; }
        public int statusValunteerId { get; set; }
        public System.DateTime silencingRingingUntilDate { get; set; }
        public System.DateTime silencingRingingFromDate { get; set; }
        public Nullable<int> volunteerId { get; set; }
    
        public virtual Valunteer Valunteer { get; set; }
    }
}
