//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HashomrimProjectEntities2 : DbContext
    {
        public HashomrimProjectEntities2()
            : base("name=HashomrimProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Callling> Calllings { get; set; }
        public virtual DbSet<DetailsValunteer> DetailsValunteers { get; set; }
        public virtual DbSet<EventName> EventNames { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventStatu> EventStatus { get; set; }
        public virtual DbSet<FreindlyEvent> FreindlyEvents { get; set; }
        public virtual DbSet<HistoryStatusValunteer> HistoryStatusValunteers { get; set; }
        public virtual DbSet<Mokdan> Mokdans { get; set; }
        public virtual DbSet<PersonalSituation> PersonalSituations { get; set; }
        public virtual DbSet<StatusValunteer> StatusValunteers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Valunteer> Valunteers { get; set; }
        public virtual DbSet<ValunteerEvent> ValunteerEvents { get; set; }
        public virtual DbSet<ValunteerStatusInEvent> ValunteerStatusInEvents { get; set; }
    }
}
